version: '2'

volumes:
  pg-data:
    driver: local
  assets:
    driver: local
    external: false

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: bundle exec rake start:production
    environment:
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      COPL_POSTGRES_PASSWORD: $COPL_POSTGRES_PASSWORD
      COPL_POSTGRES_USER: $COPL_POSTGRES_USER
    volumes:
      - assets:/opt/coplannery/public
    links:
      - db
    expose:
      - "3000"
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $COPL_POSTGRES_PASSWORD
      POSTGRES_USER: $COPL_POSTGRES_USER
  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
